[package]
name = "agdb_ci"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
agdb = { version = "0.12.6", path = "../agdb", features = ["serde", "openapi"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
utoipa = "5"
